name: Deploy Pelican Site
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pelican markdown
          # Add other dependencies if needed (e.g., pelican-plugins)

      - name: Generate site
        run: pelican content -o output -s pelicanconf.py

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: output
